name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    uses: genexuslabs/reporting-controls-library/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: '20.x'
      cache: true
      publish: false
